### ISSUE TITLE
Pipes misplaced or missing on map

### ISSUE THREAD

**Issue by SoloStryker** [Eclipse-Station/NEV-Northern-Light#1478]
![bioreactor air pipe wrong](https://user-images.githubusercontent.com/46388630/116008742-0f22d680-a5e4-11eb-8a36-63801b322861.png)
![corridor air pipe missing](https://user-images.githubusercontent.com/46388630/116008743-0fbb6d00-a5e4-11eb-82a8-9830e34f4c0d.png)

Discovered these two map errors with air pipes that prevent some vents from operating - these are on map load.
In the bioreactor room a 3-way manifold is rotated incorrectly, in a section of corridor near the holodeck several tiles of pipe are missing - see pictures.

**Comment by EvilJackCarver** [comment]
![image](https://user-images.githubusercontent.com/1784490/116013345-61b8be80-a5f5-11eb-9304-497d0d82d970.png)
I'm able to confirm the first one in the map editor, but I can't find the second one on the map. Can you give me more details as to the location?

**Comment by SoloStryker** [comment]
Not sure how to name the location - from the holodeck on deck 4 section 3 - go around it through the forward corridor - the second location is right outside the security post leading to that airlock the serb often uses?
Next time I am in byond game or editor I can try for coords or better pic

**Comment by YoteSanity** [comment]
Here is a more exhaustive list of the current piping issues as of commit f5b505f from 12 Jun 2021. Some are already known, but I'm including them all in this issue for the sake of completeness.

### 1. Church Bioreactor Room
This is the first location above mentioned by @SoloStryker with a second issue in the same room.
**88, 89, 1** - Supply manifold should be N-S-E
**84, 89, 1** - Missing E-W scrubber pipe

![Loc1_crop](https://user-images.githubusercontent.com/16764526/122688510-9c506900-d1ea-11eb-9f91-37e6187054f0.png)

### 2. Prison Wing
Lower left and upper right in the image. The manifolds feeding into the vents and scrubbers.
**87, 148, 1** - Regular manifold should be scrubber manifold
**88, 148, 1** - Regular manifold should be supply manifold
**91, 154, 1** - Regular manifold should be scrubber manifold
**92, 154, 1** - Regular manifold should be supply manifold

![Loc2_crop](https://user-images.githubusercontent.com/16764526/122688542-d6216f80-d1ea-11eb-8076-46c8faf8b2a7.png)

### 3. Section 2 Deck 3 Port Maint, south of Surgery
This one's a bit busy. It's the two tiles immediately east of the universal adapters.
**73, 116, 3** - Supply manifold should be N-S-W
**73, 115, 3** - Scrubber manifold should be scrubber 4-way manifold

![Loc3_crop](https://user-images.githubusercontent.com/16764526/122688646-7aa3b180-d1eb-11eb-8f57-82c9b72cfa45.png)

### 4. Fitness Room Back Hallway
This is the second location mentioned by @SoloStryker. Go north around the holodeck and west into the hallway behind it.
**69, [91-94], 4** - Missing sections of scrubber and supply pipes

There also appears to be a disconnected disposal T-junction at **69, 95, 4**, also pictured. I searched around a bit for something it should connect to and didn't find anything.

![Loc4_crop](https://user-images.githubusercontent.com/16764526/122688841-8e9be300-d1ec-11eb-8ffb-5820cb4de643.png)

### 5. Bar Doorway
**98, 85, 3** - Missing E-W scrubber and supply pipes

![Loc5_crop](https://user-images.githubusercontent.com/16764526/122688918-44673180-d1ed-11eb-919f-ec7e2539e88c.png)

### 6. Section 4 Deck 4 Starboard Maint, east of Old Bridge
Possibly intentional?
**108, [43-44], 4** - Missing sections of regular pipe

![Loc6_crop](https://user-images.githubusercontent.com/16764526/122692563-c95d4580-d203-11eb-881c-c504312ce3c6.png)

### 7. Medbay Break Room/Upper Corridor
**79, 106, 4** - Missing N-S scrubber pipe
**82, [103-104], 4** - Branch of supply leading to nothing

![Loc7_crop](https://user-images.githubusercontent.com/16764526/122692585-f27dd600-d203-11eb-83de-530ad851d6cb.png)

### 8. Chemistry Lab Back Doorway
**90, 108, 4** - Supply bent pipe should be E-W supply pipe

![Loc8_crop](https://user-images.githubusercontent.com/16764526/122692612-2eb13680-d204-11eb-9504-10e513aceee5.png)

### 9. Section 3 Deck 1 Central Maint, east of Clown Office
**90, 94, 5** - N-S supply pipe should be N-S-W supply manifold connecting to open end at **89, 94, 5**
**91, 94, 5** - N-S scrubber pipe should be N-S-W scrubber manifold and connected to open end at **89, 94, 5**

![Loc9_crop](https://user-images.githubusercontent.com/16764526/122692780-f8c08200-d204-11eb-91da-8eb86efd483f.png)

### 10. VIP Bar
**[87-88], [152-156], 4** - Vent connects to waste and scrubber connects to distro

![Loc10_crop](https://user-images.githubusercontent.com/16764526/122692843-32918880-d205-11eb-90ff-e822a9c5eff5.png)
