### ISSUE TITLE
Bridge Officer access discrepancies.

### ISSUE THREAD

**Issue by ExoticJazz** [Eclipse-Station/NEV-Northern-Light#1495]
Apparently the role can access most of the Brig, including both armories but is unable to enter through the 'front door' and needs to use maintenance tunnels; the only Brig related access on the card itself is 'Security Equipment'.

Has access to the Chief Science Officer's quarters and no other for some reason.

Also has full access to Atmospherics, might be the case of Atmospherics doors being classed under the general 'Engineering' access number.

**Comment by Valanthe500** [comment]
I can expand on this as I'm the one who coded them. The discrepancy you're seeing is there because the terminals on the bridge ( actually, all computer terminals) use the door access you have on your ID to determine whether you're allowed to access certain programs. In order to be able to use all the terminals on the bridge, I needed to give the Bridge Officers access to certain areas. My only other option was a complete rework of how terminals handled IDs, which is beyond my capabilities.

**Comment by EvilJackCarver** [comment]
So this is technically intended behaviour, then.

A suggestion I would make would be making a generic 'all consoles' access in code/game/jobs/access_datums.dm and making the program access requirements on a `req_one_access` list, then adjusting the BO's assigned access to handle that. The only problem then is that you'd need to test and see if the ID change console will be able to add and remove that access, and if not, figure out how to make it able to do so.

I'm flagging this as 'functions as intended', but I'll leave it open since it's something we'll need to address at some point.
