### ISSUE TITLE
Monochloramine makes me cry 

### ISSUE THREAD

**Issue by benj8560** [Eclipse-Station/NEV-Northern-Light#1639]
This gas is kinda just scuffed from what I can tell. Floor and portable scrubbers don't seem to scrub it (even tho you can set them to scrub it) and gas masks don't stop any of it's bad effects. Very rare it pops up from storyteller events or antag memes but when it does it becomes very hard to deal with once it's spread beyond a few rooms. In my case ruining a entire round it became so annoying. Also gives a oddly high amount of toxins even in very tiny amounts I did not check but I believe we where getting toxins in rooms with less then 1%

**Comment by EvilJackCarver** [comment]
Bullet points are for my own benefit:

* Floor and portables not scrubbing chloramines needs testing.
* Gas masks are an oversight on my end, currently gas masks only filter out phoron and nitrous oxide.
* The 'oddly high amount of toxins' is because it is set to add the Toxin reagent to your bloodstream; this is planned to be changed to the 'liquid chloramines' reagent in an upcoming update to a few reagents.

**Comment by benj8560** [comment]
Tested it on a freshly booted private sever. Still not scrubbing so it was not a one off thing
