### ISSUE TITLE
Ship's shield is leaking into the ship in certain locations.

### ISSUE THREAD

**Issue by ShadzFen** [Eclipse-Station/NEV-Northern-Light#400]
From what I've been told there are more locations, but this is the only one I know of. It's in the back of cargo where the airlock is next to a bunch of mining equipment. There are 3 tiles inside the ship where the shield shows up for whatever reason.

![image](https://user-images.githubusercontent.com/45645502/88293682-a11b4d00-ccfb-11ea-8080-d477ae718d4d.png)

**Comment by Acryonic** [comment]
that's just the shield diffusers freaking out when shield is set to hull shielding, activating and deactivating any of the diffusers in the area will adjust that to it going along the outer edge like it should.

**Comment by ShadzFen** [comment]
I still don't think random tiles of shield within the ship is an intended function though

**Comment by EvilJackCarver** [comment]
It actually is. The logic is that it's against a wall or a floor tile that is airless, therefore it is *probably* a part of the hull. Actually checking whether or not it is would be far too intensive, so for our purposes it'll do for now.

At the end of the day, though, this is still a notable QoL issue since you can't drag anything through them, so I'll go ahead and apply triage tags.
