### ISSUE TITLE
Clothing does not display when you take off a voidsuit.

### ISSUE THREAD

**Issue by bearrrrrrrr** [Eclipse-Station/NEV-Northern-Light#96]
![image](https://user-images.githubusercontent.com/54826962/82133433-0c0b4d80-97ba-11ea-8a5d-fea4e505a50a.png)

This only happens with...some voidsuits, sometimes, but I'm not sure why? I have encountered this when using a mining voidsuit, blood red voidsuit, and technomancer voidsuit.

**Comment by ShadzFen** [comment]
I had it happen to me with an emergency softsuit about a week ago, however I think this issue may have been patched because I can't seem to get it to happen at all. I've tried every single voidsuit and even tried doing strange things with them to see if I can trigger it but it refuses to happen anymore. 

Ultimately, I can't replicate it.
